### PR TITLE
Hulya02

### PR DESCRIPTION
**Pull request by Hulyakeles94**
Login function is done!

### CODE REVIEW

**Comment by Serghei8962** [comment]
Hulya, your codding not very easy to read

**Comment by Hulyakeles94** [comment]
Hi guys , your code is worse, please fix the bug!

**Review by Serghei8962 — CHANGES_REQUESTED** [review]
well do it again from start, open a project....

**Review by mertozer384 — CHANGES_REQUESTED** [review]
change the backround

**Pull request merged**
